service: coffee-time-bot
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  stage: ${env:stage}
  iamRoleStatements:
    -
      Effect: 'Allow'
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { 'Fn::GetAtt': ['PersistenceTable', 'Arn']}
    - Effect: Allow
      Action:
        - logs:*
      Resource:
        - 'Fn::Join':
          - ':'
          -
            - 'arn:aws:logs'
            - Ref: 'AWS::Region'
            - Ref: 'AWS::AccountId'
            - '*'
  environment:
    TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}
    REGION: us-east-1
    USER_TABLE: ${self:custom.user_table}
    BOT_NAME: ${self:custom.bot_name}
    PERSISTENCE_TABLE: ${self:custom.bot_data_table}
    MAIN_LOG_GROUP: /aws/lambda/coffe-time-bot-${env:stage}-main

package:
 patterns:
  - '!./**'
  - app/**

custom:
  pythonRequirements:
    dockerizePip: non-linux
  user_table: ${env:stage}-coffe-time-bot_users_table
  bot_data_table: ${env:stage}-coffe-time-bot_persistence_data_table
  bot_name: ${env:stage}_coffe-time-bot

plugins:
  - serverless-python-requirements
  - serverless-step-functions

functions:
  main:
    handler: app/main.main
    url: true
  schedule:
    handler: app/schedule.main
    # If you change the hour see the value of HOURS_DIFFERENCE in this file app/schedule.py
    events:
      # # -5 hours difference from UTC
      # - schedule: cron(0 30 4 ? * MON-FRI)
      # - schedule: cron(0 0 8 ? * MON-FRI)
      - schedule: cron(25 3 ? * MON-FRI *)
      - schedule: cron(30 14 ? * MON-FRI *)
      - schedule: cron(30 18 ? * MON-FRI *)

resources:
  Resources:
    ${file(resources/dynamodb.yml)}